language: ruby
rvm:
  - 2.1.5
before_install:
  - mkdir -p $TRAVIS_BUILD_DIR/vendor
  - curl -O http://pqxx.org/download/software/libpqxx/libpqxx-4.0.1.tar.gz
  - tar -xvf libpqxx-4.0.1.tar.gz
  - cd libpqxx-4.0.1
  - ./configure --prefix=$TRAVIS_BUILD_DIR/vendor
  - make
  - make install
  - cd ..
  - bundle config --local build.hmsearch-postgres -- --with-pqxx-include=$TRAVIS_BUILD_DIR/vendor/include\ --with-pqxx-lib=$TRAVIS_BUILD_DIR/vendor/lib
